# Generated by Django 4.2 on 2023-04-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=50, unique=True)),
                ('hod', models.CharField(max_length=50)),
                ('departmentType', models.CharField(max_length=50)),
                ('misCategory', models.CharField(max_length=50)),
                ('departmentCode', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=50)),
                ('employeeType', models.CharField(max_length=50)),
                ('softNumber', models.CharField(max_length=50)),
                ('payrollNumber', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('joiningDate', models.DateField()),
                ('emailId', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('renewalType', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('noticePeriodTime', models.IntegerField()),
                ('nonSbecExpTime', models.IntegerField()),
                ('presbecExpTime', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('emergencyContactNumber', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=50)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('otherBranch', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.department_tbl')),
            ],
        ),
    ]
