# Generated by Django 4.1.7 on 2023-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=50, unique=True)),
                ('hod', models.CharField(max_length=50, unique=True)),
                ('departmentType', models.CharField(max_length=50)),
                ('misCategory', models.CharField(max_length=50)),
                ('departmentCode', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
