# Generated by Django 4.1.7 on 2023-03-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_department_tbl_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=50)),
                ('employeeType', models.CharField(max_length=50)),
                ('softNumber', models.CharField(max_length=50)),
                ('payrollNumber', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('joiningDate', models.DateField()),
                ('emailId', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('renewalType', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('noticePeriodTime', models.DateField()),
                ('nonSbecExpTime', models.IntegerField()),
                ('presbecExpTime', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('emergencyContactNumber', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=50)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('otherBranch', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.department_tbl')),
            ],
        ),
    ]
