# Generated by Django 4.1.7 on 2023-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_employee_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_tbl',
            name='noticePeriodTime',
            field=models.IntegerField(),
        ),
    ]
