# Generated by Django 4.1.7 on 2023-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_employee_tbl_noticeperiodtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_tbl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
